name: upload-artifact

on:
  push:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: pnpm run zip

      - name: Build project for Safari
        run: pnpm wxt build -b safari

      - name: Convert to Safari Web Extension
        run: xcrun safari-web-extension-converter .output/safari-mv2

      - name: show .output files
        run: ls -la .output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: furigana-maker-exts
          path: .output/